In [43]:
import numpy as np

In [44]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [45]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
o = np.ones((3,4), dtype = int)
o2 = np.zeros((3,4), dtype = int)
o3 = np.ones((3,4), dtype = int)*3

print(o,o2,o3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [47]:
o = np.full((3,4),9,dtype=int)
print(o)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [48]:
# random full
o = np.full((3,4),np.random.randint(1,10),dtype=int)
print(o)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [49]:
#random matrix
rand = np.random.randint(1,11,size=(4,4))
rand

array([[7, 7, 2, 8],
       [5, 8, 2, 8],
       [8, 4, 3, 1],
       [2, 2, 4, 4]])

In [50]:
r = np.random.random((3,4))
print(r,end="\n")

r = 30+(50-30)*np.random.random((3,4))
print(r,"\n","\n",r/100)

[[0.07706929 0.90800183 0.25056827 0.30583747]
 [0.39790943 0.42307882 0.15188859 0.473677  ]
 [0.5567279  0.910807   0.03555591 0.97170276]]
[[34.08797171 38.31179878 44.94069265 32.606648  ]
 [30.79511942 36.09502384 39.82785735 40.2795817 ]
 [46.87766729 49.33332521 35.40006794 47.04913265]] 
 
 [[0.34087972 0.38311799 0.44940693 0.32606648]
 [0.30795119 0.36095024 0.39827857 0.40279582]
 [0.46877667 0.49333325 0.35400068 0.47049133]]


In [51]:
ar = np.arange(0,101,5) #(start,end+1,steps)
ar

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [52]:
#Equal Spaces between the starting and the end
li = np.linspace(10,100,11)
li

array([ 10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91., 100.])

In [53]:
# array inspection

print(o.shape) #shape eg.(3,3)
print(o.size)
print(o.ndim)

(3, 4)
12
2


In [54]:
cube = np.zeros((3,3,3),dtype=int)
print(cube)

print(cube.ndim)
print(cube.dtype)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
3
int64


In [55]:
#Modify Shape
o.shape = (1,12)
print(o)

[[1 1 1 1 1 1 1 1 1 1 1 1]]


In [56]:

o = o.reshape(12,1)
print(o)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [57]:
#Math Funcs

print("Exponents of an array", np.exp(rand))
print("log of an array", np.log(rand))
print("Square root of an array", np.sqrt(rand))
#mean 
#median 
#std
print("Power", np.power(rand,2))

Exponents of an array [[1.09663316e+03 1.09663316e+03 7.38905610e+00 2.98095799e+03]
 [1.48413159e+02 2.98095799e+03 7.38905610e+00 2.98095799e+03]
 [2.98095799e+03 5.45981500e+01 2.00855369e+01 2.71828183e+00]
 [7.38905610e+00 7.38905610e+00 5.45981500e+01 5.45981500e+01]]
log of an array [[1.94591015 1.94591015 0.69314718 2.07944154]
 [1.60943791 2.07944154 0.69314718 2.07944154]
 [2.07944154 1.38629436 1.09861229 0.        ]
 [0.69314718 0.69314718 1.38629436 1.38629436]]
Square root of an array [[2.64575131 2.64575131 1.41421356 2.82842712]
 [2.23606798 2.82842712 1.41421356 2.82842712]
 [2.82842712 2.         1.73205081 1.        ]
 [1.41421356 1.41421356 2.         2.        ]]
Power [[49 49  4 64]
 [25 64  4 64]
 [64 16  9  1]
 [ 4  4 16 16]]


In [58]:
rand

array([[7, 7, 2, 8],
       [5, 8, 2, 8],
       [8, 4, 3, 1],
       [2, 2, 4, 4]])

In [59]:
rand[::,:2:]

array([[7, 7],
       [5, 8],
       [8, 4],
       [2, 2]])

In [60]:
np.sum([[1,2],[5,6]])

np.int64(14)

In [61]:
a = np.array([[1,2],[4,5]])
b = np.array([[10,20],[40,50]])


In [62]:
np.add(a,b)

array([[11, 22],
       [44, 55]])

In [63]:
np.divide(a,b)

array([[0.1, 0.1],
       [0.1, 0.1]])

In [64]:
np.subtract(a,b)

array([[ -9, -18],
       [-36, -45]])

In [65]:
np.multiply(a,b)

array([[ 10,  40],
       [160, 250]])

In [66]:
a = np.array([1,2,3])
b = np.array([10,20,30])
c = np.array([1,2,3])

np.array_equal(a,b)
np.equal(a,c)

array([ True,  True,  True])

In [ ]:
np.hstack((a,b))
np.vstack((a,c))    

array([[1, 2, 3],
       [1, 2, 3]])

In [69]:
np.column_stack((a,b,c))

array([[ 1, 10,  1],
       [ 2, 20,  2],
       [ 3, 30,  3]])